# KUKA Feature Selection Experiments

This notebook is organized into clearly separated parts:

- **Part A — Shared setup and reusable helpers**
- **Part B — AE feature-selection experiments**
- **Part C — AAE baseline feature-selection experiments**

In [16]:
from pathlib import Path
import sys
import random

import numpy as np
import pandas as pd

import torch
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "dataset").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.insert(0, str(PROJECT_ROOT))

from dataset.kuka_splits import split_kuka_numpy
from dataset.kuka_dataset import KukaDataset
from processing.kuka_processing import KukaPreprocessor
from models.AE import AE
from metrics import compute_pr_auc

## Part A.1 — Configuration

In [18]:
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
RESULTS_DIR.mkdir(exist_ok=True)

SEED = 123
BATCH_SIZE = 1024
LATENT_DIM = 4
LR = 1e-3
EPOCHS = 50          # increase for final runs, e.g. 300 or 1500
TOP_K = 5
F_BETA = 2.0

CONSTANT_EPS = 1e-8
CORR_THRESHOLD = 0.98
M_VALUES = [10, 20, 40, 60]

DEVICE = torch.device("cpu")
DEVICE

device(type='cpu')

In [19]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(SEED)

## Part A.2 — Load dataset split

In [20]:
splits = split_kuka_numpy(DATA_DIR, seed=SEED, binary_labels=True)

print("x_train:", splits.x_train.shape, "y_train:", splits.y_train.shape, np.unique(splits.y_train, return_counts=True))
print("x_val:  ", splits.x_val.shape,   "y_val:  ", splits.y_val.shape,   np.unique(splits.y_val, return_counts=True))
print("x_test: ", splits.x_test.shape,  "y_test: ", splits.y_test.shape,  np.unique(splits.y_test, return_counts=True))

n_features_raw = splits.x_train.shape[1]
print("Raw feature count:", n_features_raw)

x_train: (163654, 86) y_train: (163654,) (array([0], dtype=int64), array([163654], dtype=int64))
x_val:   (55837, 86) y_val:   (55837,) (array([0, 1], dtype=int64), array([35068, 20769], dtype=int64))
x_test:  (55839, 86) y_test:  (55839,) (array([0, 1], dtype=int64), array([35070, 20769], dtype=int64))
Raw feature count: 86

## Part A.3 — Load feature names

In [21]:
def load_feature_names(data_dir: Path, n_features: int) -> np.ndarray:
    path = data_dir / "KukaColumnNames.npy"

    if not path.exists():
        print("KukaColumnNames.npy not found. Using generic feature names.")
        return np.array([f"feature_{i}" for i in range(n_features)], dtype=object)

    names = np.load(path, allow_pickle=True).astype(str)

    if len(names) == n_features:
        return names

    if len(names) == n_features + 1:
        print("Feature-name file has one extra column. Assuming last entry is label and dropping it.")
        return names[:-1]

    print(f"Unexpected number of feature names: {len(names)} for {n_features} features. Using generic feature names.")
    return np.array([f"feature_{i}" for i in range(n_features)], dtype=object)

feature_names = load_feature_names(DATA_DIR, n_features_raw)
assert len(feature_names) == n_features_raw

pd.DataFrame({"feature_index": np.arange(n_features_raw), "feature_name": feature_names}).head(10)

Feature-name file has one extra column. Assuming last entry is label and dropping it.

   feature_index                           feature_name
0              0                                 action
1              1  machine_nameKuka Robot_apparent_power
2              2         machine_nameKuka Robot_current
3              3       machine_nameKuka Robot_frequency
4              4     machine_nameKuka Robot_phase_angle
5              5           machine_nameKuka Robot_power
6              6    machine_nameKuka Robot_power_factor
7              7  machine_nameKuka Robot_reactive_power
8              8         machine_nameKuka Robot_voltage
9              9                        sensor_id1_AccX

## Part A.4 — Shared AE utility functions

These functions support the AE experiments in Part B.

In [22]:
def make_dataloaders_for_features(selected_features, batch_size=BATCH_SIZE, normalization=True):
    """Build DataLoaders for a selected subset of original feature indices."""
    selected_features = np.asarray(selected_features, dtype=int)

    x_train_raw = splits.x_train[:, selected_features]
    x_val_raw = splits.x_val[:, selected_features]
    x_test_raw = splits.x_test[:, selected_features]

    preprocessor = KukaPreprocessor(
        normalization=normalization,
        remove_constant=False,
        corr_threshold=None,
        clip_percentiles=None,
    )

    x_train = preprocessor.fit_transform(x_train_raw)
    x_val = preprocessor.transform(x_val_raw)
    x_test = preprocessor.transform(x_test_raw)

    train_dataset = KukaDataset(x_train, splits.y_train)
    val_dataset = KukaDataset(x_val, splits.y_val)
    test_dataset = KukaDataset(x_test, splits.y_test)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader, preprocessor


def ae_error_fn(pred, x, top_k=TOP_K):
    k = min(int(top_k), x.shape[1])
    return (pred - x).pow(2).topk(k, dim=1).values.mean(dim=1)


def train_ae_model(model, train_loader, device=DEVICE, lr=LR, epochs=EPOCHS):
    loss_fn = torch.nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    history = []
    model.to(device)

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0

        for x, _ in train_loader:
            x = x.to(device)
            optimizer.zero_grad()
            recon = model(x)
            loss = loss_fn(recon, x)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        epoch_loss = running_loss / len(train_loader)
        history.append(epoch_loss)

        if epoch == 0 or (epoch + 1) % max(1, epochs // 5) == 0 or epoch == epochs - 1:
            print(f"Epoch {epoch + 1:4d}/{epochs}: loss={epoch_loss:.6f}")

    return history

@torch.no_grad()
def compute_reconstruction_error_scores(model, dataloader, recon_top_k):
    recon_scores = []
    labels = []

    model.eval()
    for x, y in dataloader:
        recon = model(x)
        
        if isinstance(recon, tuple):
            recon = recon[0]

        # reconstruction error score
        recon_score = (recon - x).pow(2).topk(recon_top_k, dim=1).values.mean(dim=1)

        recon_scores.append(recon_score.cpu())
        labels.append(y.cpu())

    recon_scores = torch.cat(recon_scores)
    labels = torch.cat(labels)

    return recon_scores, labels


def run_ae_experiment(experiment_name, selected_features, epochs=EPOCHS, seed=SEED):
    """Train and evaluate an AE on a specific feature subset."""
    selected_features = np.asarray(selected_features, dtype=int)

    if len(selected_features) == 0:
        raise ValueError(f"{experiment_name}: selected feature subset is empty")

    print("=" * 80)
    print(f"Experiment: {experiment_name}")
    print(f"Selected features: {len(selected_features)}")

    set_seed(seed)

    train_loader, val_loader, test_loader, preprocessor = make_dataloaders_for_features(selected_features)

    input_dim = len(selected_features)
    model = AE(input_dim, LATENT_DIM).to(DEVICE)

    history = train_ae_model(model, train_loader, epochs=epochs)

    
    scores, labels = compute_reconstruction_error_scores(model, val_loader, TOP_K)

    pr_auc = compute_pr_auc(
        scores=scores,
        labels=labels
    )

    row = {
        "experiment": experiment_name,
        "n_features": int(len(selected_features)),
        "pr_auc": pr_auc
    }

    print(pd.Series(row))

    return {
        "row": row,
        "model": model,
        "history": history,
        "selected_features": selected_features,
        "preprocessor": preprocessor,
        "labels": labels,
    }

## Part A.5 — Shared feature-selection functions

In [23]:
def select_all_features(n_features: int) -> np.ndarray:
    return np.arange(n_features, dtype=int)


def select_nonconstant_features(x_train, eps=CONSTANT_EPS) -> np.ndarray:
    std = np.std(x_train, axis=0)
    return np.flatnonzero(std > eps)


def correlation_prune_features(x_train, candidate_features, threshold=CORR_THRESHOLD) -> np.ndarray:
    """Greedy correlation pruning in the order given by candidate_features."""
    candidate_features = np.asarray(candidate_features, dtype=int)
    x = x_train[:, candidate_features]

    if x.shape[1] <= 1:
        return candidate_features

    corr = np.corrcoef(x, rowvar=False)
    corr = np.nan_to_num(np.abs(corr), nan=0.0, posinf=0.0, neginf=0.0)

    keep_local = []
    for j in range(x.shape[1]):
        if not keep_local:
            keep_local.append(j)
            continue

        max_corr = np.max(corr[j, keep_local])
        if max_corr <= threshold:
            keep_local.append(j)

    return candidate_features[np.array(keep_local, dtype=int)]


def ks_statistic_1d(a, b):
    """Two-sample KS statistic D. Does not require scipy."""
    a = np.sort(np.asarray(a, dtype=float))
    b = np.sort(np.asarray(b, dtype=float))

    if len(a) == 0 or len(b) == 0:
        return np.nan

    values = np.concatenate([a, b])
    cdf_a = np.searchsorted(a, values, side="right") / len(a)
    cdf_b = np.searchsorted(b, values, side="right") / len(b)
    return float(np.max(np.abs(cdf_a - cdf_b)))


def rank_features_by_ks(x_val, y_val, candidate_features):
    candidate_features = np.asarray(candidate_features, dtype=int)
    y_val = np.asarray(y_val).astype(int)

    normal_mask = y_val == 0
    anomaly_mask = y_val == 1

    if normal_mask.sum() == 0 or anomaly_mask.sum() == 0:
        raise ValueError("Validation split must contain both normal and anomaly samples for KS ranking.")

    scores = []
    for f in candidate_features:
        scores.append(ks_statistic_1d(x_val[normal_mask, f], x_val[anomaly_mask, f]))

    scores = np.asarray(scores)
    order = np.argsort(scores)[::-1]

    return candidate_features[order], scores[order]


def rank_features_by_ae_reconstruction_separation(model, val_loader, candidate_features, eps=1e-8):
    """
    Rank selected input features by validation reconstruction-error separation:

        r_j = (mean_anomaly_error_j - mean_normal_error_j) / (std_normal_error_j + eps)

    candidate_features maps local model columns back to original feature indices.
    """
    model.eval()

    normal_errors = []
    anomaly_errors = []

    with torch.no_grad():
        for x, y in val_loader:
            x = x.to(DEVICE)
            recon = model(x)
            feature_err = (recon - x).pow(2).cpu()

            y = y.cpu()
            if (y == 0).any():
                normal_errors.append(feature_err[y == 0])
            if (y == 1).any():
                anomaly_errors.append(feature_err[y == 1])

    if not normal_errors or not anomaly_errors:
        raise ValueError("Validation split must contain both normal and anomaly samples.")

    normal_errors = torch.cat(normal_errors, dim=0)
    anomaly_errors = torch.cat(anomaly_errors, dim=0)

    normal_mean = normal_errors.mean(dim=0)
    normal_std = normal_errors.std(dim=0)
    anomaly_mean = anomaly_errors.mean(dim=0)

    separation = ((anomaly_mean - normal_mean) / (normal_std + eps)).numpy()
    order = np.argsort(separation)[::-1]

    candidate_features = np.asarray(candidate_features, dtype=int)
    return candidate_features[order], separation[order]

# Part B — AE feature-selection experiments

## Part B.1 — Build AE feature subsets

In [19]:
all_features = select_all_features(n_features_raw)
nonconstant_features = select_nonconstant_features(splits.x_train, eps=CONSTANT_EPS)
nonconstant_corr_features = correlation_prune_features(
    splits.x_train,
    nonconstant_features,
    threshold=CORR_THRESHOLD,
)

print("All features:                 ", len(all_features))
print("After near-constant removal:  ", len(nonconstant_features))
print("After correlation pruning:    ", len(nonconstant_corr_features))

removed_constant = np.setdiff1d(all_features, nonconstant_features)
removed_corr = np.setdiff1d(nonconstant_features, nonconstant_corr_features)

print("Near-constant removed:")
display(pd.DataFrame({"feature_index": removed_constant, "feature_name": feature_names[removed_constant]}))

print("Correlation-pruned removed, first 20:")
display(pd.DataFrame({"feature_index": removed_corr[:20], "feature_name": feature_names[removed_corr[:20]]}))

All features:                  86
After near-constant removal:   82
After correlation pruning:     79
Near-constant removed:

   feature_index     feature_name
0             30  sensor_id2_temp
1             63  sensor_id5_temp
2             74  sensor_id6_temp
3             85  sensor_id7_temp

Correlation-pruned removed, first 20:

   feature_index                         feature_name
0              5         machine_nameKuka Robot_power
1              6  machine_nameKuka Robot_power_factor
2             80                     sensor_id7_GyroZ

In [20]:
# KS ranking uses validation labels only.
# Use nonconstant features as candidates to avoid selecting degenerate channels.

ks_ranked_features, ks_scores = rank_features_by_ks(
    splits.x_val,
    splits.y_val,
    candidate_features=nonconstant_features,
)

ks_table = pd.DataFrame({
    "rank": np.arange(1, len(ks_ranked_features) + 1),
    "feature_index": ks_ranked_features,
    "feature_name": feature_names[ks_ranked_features],
    "ks_score": ks_scores,
})

ks_table.head(20)

    rank  feature_index                         feature_name  ks_score
0      1             37                        sensor_id3_q1  0.444422
1      2             17                        sensor_id1_q3  0.413103
2      3             15                        sensor_id1_q1  0.411799
3      4             72                        sensor_id6_q3  0.395636
4      5             71                        sensor_id6_q2  0.359868
5      6             38                        sensor_id3_q2  0.357046
6      7              8       machine_nameKuka Robot_voltage  0.335216
7      8             50                        sensor_id4_q3  0.333629
8      9              4   machine_nameKuka Robot_phase_angle  0.308354
9     10              6  machine_nameKuka Robot_power_factor  0.308327
10    11             49                        sensor_id4_q2  0.306350
11    12             48                        sensor_id4_q1  0.287643
12    13             83                        sensor_id7_q3  0.286905
13    14             62                        sensor_id5_q4  0.272725
14    15             18                        sensor_id1_q4  0.262092
15    16             73                        sensor_id6_q4  0.261393
16    17             82                        sensor_id7_q2  0.259256
17    18             60                        sensor_id5_q2  0.237628
18    19             39                        sensor_id3_q3  0.237269
19    20             28                        sensor_id2_q3  0.212113

## Part B.2 — Run AE experiments for all, nonconstant, correlation-pruned and KS-selected features

In [21]:
experiment_outputs = []
selected_feature_tables = {}

out_all = run_ae_experiment("all_features", all_features, epochs=EPOCHS, seed=SEED)
experiment_outputs.append(out_all)
selected_feature_tables["all_features"] = all_features

out_nc = run_ae_experiment("nonconstant", nonconstant_features, epochs=EPOCHS, seed=SEED)
experiment_outputs.append(out_nc)
selected_feature_tables["nonconstant"] = nonconstant_features

out_nc_corr = run_ae_experiment("nonconstant_corr", nonconstant_corr_features, epochs=EPOCHS, seed=SEED)
experiment_outputs.append(out_nc_corr)
selected_feature_tables["nonconstant_corr"] = nonconstant_corr_features

for m in M_VALUES:
    m_eff = min(m, len(ks_ranked_features))
    selected = ks_ranked_features[:m_eff]
    name = f"top_{m_eff}_ks"
    out = run_ae_experiment(name, selected, epochs=EPOCHS, seed=SEED)
    experiment_outputs.append(out)
    selected_feature_tables[name] = selected

================================================================================
Experiment: all_features
Selected features: 86
Epoch    1/50: loss=0.062107
Epoch   10/50: loss=0.018654
Epoch   20/50: loss=0.016381
Epoch   30/50: loss=0.014690
Epoch   40/50: loss=0.013837
Epoch   50/50: loss=0.013143
experiment    all_features
n_features              86
pr_auc            0.722222
dtype: object
================================================================================
Experiment: nonconstant
Selected features: 82
Epoch    1/50: loss=0.061263
Epoch   10/50: loss=0.017505
Epoch   20/50: loss=0.015494
Epoch   30/50: loss=0.012855
Epoch   40/50: loss=0.011900
Epoch   50/50: loss=0.011292
experiment    nonconstant
n_features             82
pr_auc            0.67768
dtype: object
================================================================================
Experiment: nonconstant_corr
Selected features: 79
Epoch    1/50: loss=0.065274
Epoch   10/50: loss=0.019475
Epoch   20/50: loss=0.016421
Epoch   30/50: loss=0.014584
Epoch   40/50: loss=0.013561
Epoch   50/50: loss=0.012818
experiment    nonconstant_corr
n_features                  79
pr_auc                0.711392
dtype: object
================================================================================
Experiment: top_10_ks
Selected features: 10
Epoch    1/50: loss=0.098795
Epoch   10/50: loss=0.005418
Epoch   20/50: loss=0.004629
Epoch   30/50: loss=0.004343
Epoch   40/50: loss=0.004080
Epoch   50/50: loss=0.002956
experiment    top_10_ks
n_features           10
pr_auc         0.797754
dtype: object
================================================================================
Experiment: top_20_ks
Selected features: 20
Epoch    1/50: loss=0.089451
Epoch   10/50: loss=0.019846
Epoch   20/50: loss=0.016075
Epoch   30/50: loss=0.014107
Epoch   40/50: loss=0.012849
Epoch   50/50: loss=0.011928
experiment    top_20_ks
n_features           20
pr_auc         0.832197
dtype: object
================================================================================
Experiment: top_40_ks
Selected features: 40
Epoch    1/50: loss=0.079251
Epoch   10/50: loss=0.022958
Epoch   20/50: loss=0.019063
Epoch   30/50: loss=0.017360
Epoch   40/50: loss=0.014684
Epoch   50/50: loss=0.012704
experiment    top_40_ks
n_features           40
pr_auc         0.808333
dtype: object
================================================================================
Experiment: top_60_ks
Selected features: 60
Epoch    1/50: loss=0.067903
Epoch   10/50: loss=0.018890
Epoch   20/50: loss=0.016468
Epoch   30/50: loss=0.015129
Epoch   40/50: loss=0.014403
Epoch   50/50: loss=0.013835
experiment    top_60_ks
n_features           60
pr_auc          0.76213
dtype: object

## Part B.3 — Rank features by AE reconstruction-error separation

This method first trains an AE on the correlation-pruned candidate feature space, then ranks features using validation reconstruction-error separation:

$$
r_j = \frac{\mu_{anom,j}-\mu_{normal,j}}{\sigma_{normal,j}+\epsilon}.
$$

In [22]:
base_model_for_recon_ranking = out_nc_corr["model"]
base_candidate_features = nonconstant_corr_features

_, val_loader_for_base, _, _ = make_dataloaders_for_features(base_candidate_features)

ae_ranked_features, ae_sep_scores = rank_features_by_ae_reconstruction_separation(
    base_model_for_recon_ranking,
    val_loader_for_base,
    candidate_features=base_candidate_features,
)

ae_sep_table = pd.DataFrame({
    "rank": np.arange(1, len(ae_ranked_features) + 1),
    "feature_index": ae_ranked_features,
    "feature_name": feature_names[ae_ranked_features],
    "ae_reconstruction_separation": ae_sep_scores,
})

ae_sep_table.head(20)

,rank,feature_index,feature_name,ae_reconstruction_separation
0,1,50,sensor_id4_q3,12.993514
1,2,48,sensor_id4_q1,10.264585
2,3,49,sensor_id4_q2,6.606115
3,4,51,sensor_id4_q4,4.698593
4,5,60,sensor_id5_q2,2.014117
5,6,62,sensor_id5_q4,1.920820
6,7,38,sensor_id3_q2,1.320322
7,8,83,sensor_id7_q3,0.863053
8,9,82,sensor_id7_q2,0.700471
9,10,84,sensor_id7_q4,0.660610
10,11,72,sensor_id6_q3,0.645609
11,12,3,machine_nameKuka Robot_frequency,0.352059
12,13,27,sensor_id2_q2,0.350702
13,14,4,machine_nameKuka Robot_phase_angle,0.307641
14,15,71,sensor_id6_q2,0.294608
15,16,29,sensor_id2_q4,0.291875
16,17,40,sensor_id3_q4,0.275453
17,18,81,sensor_id7_q1,0.223666
18,19,61,sensor_id5_q3,0.199260
19,20,8,machine_nameKuka Robot_voltage,0.193831

## Part B.4 — Run AE experiments for reconstruction-separation selected features

This cell evaluates top-$m$ subsets selected by the AE reconstruction-error separation ranking.

In [23]:
for m in M_VALUES:
    m_eff = min(m, len(ae_ranked_features))
    selected = ae_ranked_features[:m_eff]
    name = f"top_{m_eff}_ae_recon_sep"
    out = run_ae_experiment(name, selected, epochs=EPOCHS, seed=SEED)
    experiment_outputs.append(out)
    selected_feature_tables[name] = selected

================================================================================
Experiment: top_10_ae_recon_sep
Selected features: 10
Epoch    1/50: loss=0.110249
Epoch   10/50: loss=0.011237
Epoch   20/50: loss=0.008962
Epoch   30/50: loss=0.008278
Epoch   40/50: loss=0.007318
Epoch   50/50: loss=0.007002
experiment    top_10_ae_recon_sep
n_features                     10
pr_auc                   0.724544
dtype: object
================================================================================
Experiment: top_20_ae_recon_sep
Selected features: 20
Epoch    1/50: loss=0.080117
Epoch   10/50: loss=0.019911
Epoch   20/50: loss=0.015579
Epoch   30/50: loss=0.013996
Epoch   40/50: loss=0.013073
Epoch   50/50: loss=0.011484
experiment    top_20_ae_recon_sep
n_features                     20
pr_auc                   0.776479
dtype: object
================================================================================
Experiment: top_40_ae_recon_sep
Selected features: 40
Epoch    1/50: loss=0.076402
Epoch   10/50: loss=0.021831
Epoch   20/50: loss=0.018337
Epoch   30/50: loss=0.016039
Epoch   40/50: loss=0.014747
Epoch   50/50: loss=0.013819
experiment    top_40_ae_recon_sep
n_features                     40
pr_auc                   0.892075
dtype: object
================================================================================
Experiment: top_60_ae_recon_sep
Selected features: 60
Epoch    1/50: loss=0.066569
Epoch   10/50: loss=0.017996
Epoch   20/50: loss=0.016368
Epoch   30/50: loss=0.015540
Epoch   40/50: loss=0.014759
Epoch   50/50: loss=0.013964
experiment    top_60_ae_recon_sep
n_features                     60
pr_auc                    0.73154
dtype: object

## Part B.5 — AE results summary

In [26]:
results_df = pd.DataFrame([out["row"] for out in experiment_outputs])

results_df.sort_values("pr_auc", ascending=False)

             experiment  n_features    pr_auc
9   top_40_ae_recon_sep          40  0.892075
4             top_20_ks          20  0.832197
5             top_40_ks          40  0.808333
3             top_10_ks          10  0.797754
8   top_20_ae_recon_sep          20  0.776479
6             top_60_ks          60  0.762130
10  top_60_ae_recon_sep          60  0.731540
7   top_10_ae_recon_sep          10  0.724544
0          all_features          86  0.722222
2      nonconstant_corr          79  0.711392
1           nonconstant          82  0.677680

## Part B.6 — Save AE feature-selection outputs

In [27]:
results_path = RESULTS_DIR / "feature_selection_results.csv"
ks_path = RESULTS_DIR / "feature_selection_ks_ranking.csv"
ae_sep_path = RESULTS_DIR / "feature_selection_ae_recon_sep_ranking.csv"
selected_path = RESULTS_DIR / "feature_selection_selected_features.csv"

results_df.to_csv(results_path, index=False)
ks_table.to_csv(ks_path, index=False)
ae_sep_table.to_csv(ae_sep_path, index=False)

selected_rows = []
for experiment, indices in selected_feature_tables.items():
    for rank, idx in enumerate(indices, start=1):
        selected_rows.append({
            "experiment": experiment,
            "rank": rank,
            "feature_index": int(idx),
            "feature_name": str(feature_names[idx]),
        })

selected_df = pd.DataFrame(selected_rows)
selected_df.to_csv(selected_path, index=False)

print("Saved results.")

Saved results.

## Part B.7 — Inspect AE selected features

In [29]:
EXPERIMENT_TO_INSPECT = "top_40_ae_recon_sep"

if EXPERIMENT_TO_INSPECT in selected_feature_tables:
    idx = selected_feature_tables[EXPERIMENT_TO_INSPECT]
    display(pd.DataFrame({
        "rank": np.arange(1, len(idx) + 1),
        "feature_index": idx,
        "feature_name": feature_names[idx],
    }))
else:
    print("Available experiments:")
    print(list(selected_feature_tables.keys()))

    rank  feature_index                        feature_name
0      1             50                       sensor_id4_q3
1      2             48                       sensor_id4_q1
2      3             49                       sensor_id4_q2
3      4             51                       sensor_id4_q4
4      5             60                       sensor_id5_q2
5      6             62                       sensor_id5_q4
6      7             38                       sensor_id3_q2
7      8             83                       sensor_id7_q3
8      9             82                       sensor_id7_q2
9     10             84                       sensor_id7_q4
10    11             72                       sensor_id6_q3
11    12              3    machine_nameKuka Robot_frequency
12    13             27                       sensor_id2_q2
13    14              4  machine_nameKuka Robot_phase_angle
14    15             71                       sensor_id6_q2
15    16             29                       sensor_id2_q4
16    17             40                       sensor_id3_q4
17    18             81                       sensor_id7_q1
18    19             61                       sensor_id5_q3
19    20              8      machine_nameKuka Robot_voltage
20    21             16                       sensor_id1_q2
21    22              0                              action
22    23             70                       sensor_id6_q1
23    24             28                       sensor_id2_q3
24    25             39                       sensor_id3_q3
25    26             59                       sensor_id5_q1
26    27             18                       sensor_id1_q4
27    28             22                     sensor_id2_AccZ
28    29             73                       sensor_id6_q4
29    30             26                       sensor_id2_q1
30    31             32                     sensor_id3_AccY
31    32             44                     sensor_id4_AccZ
32    33             31                     sensor_id3_AccX
33    34             35                    sensor_id3_GyroY
34    35             42                     sensor_id4_AccX
35    36             34                    sensor_id3_GyroX
36    37             19                     sensor_id1_temp
37    38             43                     sensor_id4_AccY
38    39             15                       sensor_id1_q1
39    40             10                     sensor_id1_AccY

# Part C — AAE baseline feature-selection experiments

This part implements feature selection for the Adversarial Autoencoder.

## Part C.1 — AAE imports and configuration

In [25]:
from models.AAE import AAE
from train_aae import train as train_aae_model

AAE_SEED = SEED
AAE_BATCH_SIZE = BATCH_SIZE
AAE_LATENT_DIM = LATENT_DIM
AAE_EPOCHS = EPOCHS
AAE_TOP_K = TOP_K

AAE_LR_AE = 1e-3
AAE_LR_D = 5e-5
AAE_LR_G = 1e-4

AAE_RESULTS_PATH = RESULTS_DIR / "feature_selection_aae_baseline_results.csv"
AAE_SELECTED_PATH = RESULTS_DIR / "feature_selection_aae_selected_features.csv"
AAE_KS_PATH = RESULTS_DIR / "feature_selection_aae_ks_ranking.csv"
AAE_RECON_SEP_PATH = RESULTS_DIR / "feature_selection_aae_recon_sep_ranking.csv"

## Part C.2 — Load AAE-specific split and feature names

In [26]:
aae_splits = split_kuka_numpy(DATA_DIR, seed=AAE_SEED, binary_labels=True)

aae_n_features_raw = aae_splits.x_train.shape[1]
aae_feature_names = load_feature_names(DATA_DIR, aae_n_features_raw)

print("AAE x_train:", aae_splits.x_train.shape, "y_train:", aae_splits.y_train.shape, np.unique(aae_splits.y_train, return_counts=True))
print("AAE x_val:  ", aae_splits.x_val.shape, "y_val:  ", aae_splits.y_val.shape, np.unique(aae_splits.y_val, return_counts=True))
print("AAE x_test: ", aae_splits.x_test.shape, "y_test: ", aae_splits.y_test.shape, np.unique(aae_splits.y_test, return_counts=True))

Feature-name file has one extra column. Assuming last entry is label and dropping it.
AAE x_train: (163654, 86) y_train: (163654,) (array([0], dtype=int64), array([163654], dtype=int64))
AAE x_val:   (55837, 86) y_val:   (55837,) (array([0, 1], dtype=int64), array([35068, 20769], dtype=int64))
AAE x_test:  (55839, 86) y_test:  (55839,) (array([0, 1], dtype=int64), array([35070, 20769], dtype=int64))

## Part C.3 — AAE-specific dataloaders and scoring helpers

The AAE baseline score is reconstruction-only:

$$
s_{AAE,rec}(x)=\frac{1}{k}\sum_{r=1}^{k} e_{(r)}(x).
$$

In [27]:
def make_aae_dataloaders_for_features(selected_features, batch_size=AAE_BATCH_SIZE, normalization=True):
    # Build AAE DataLoaders for a selected subset of original feature indices.
    selected_features = np.asarray(selected_features, dtype=int)

    x_train_raw = aae_splits.x_train[:, selected_features]
    x_val_raw = aae_splits.x_val[:, selected_features]
    x_test_raw = aae_splits.x_test[:, selected_features]

    preprocessor = KukaPreprocessor(
        normalization=normalization,
        remove_constant=False,
        corr_threshold=None,
        clip_percentiles=None,
    )

    x_train = preprocessor.fit_transform(x_train_raw)
    x_val = preprocessor.transform(x_val_raw)
    x_test = preprocessor.transform(x_test_raw)

    train_dataset = KukaDataset(x_train, aae_splits.y_train)
    val_dataset = KukaDataset(x_val, aae_splits.y_val)
    test_dataset = KukaDataset(x_test, aae_splits.y_test)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader, preprocessor


@torch.no_grad()
def compute_aae_reconstruction_scores(model, dataloader, recon_top_k=AAE_TOP_K):
    # Compute top-k reconstruction scores for an AAE model without fusion.
    scores = []
    labels = []

    model.eval()
    device = next(model.parameters()).device

    for x, y in dataloader:
        x = x.float().to(device)
        recon, _ = model(x)
        k = min(int(recon_top_k), x.shape[1])
        score = (recon - x).pow(2).topk(k, dim=1).values.mean(dim=1)

        scores.append(score.detach().cpu())
        labels.append(y.cpu())

    return torch.cat(scores), torch.cat(labels)


def run_aae_baseline_experiment(experiment_name, selected_features, epochs=AAE_EPOCHS, seed=AAE_SEED):
    # Train and evaluate an AAE baseline on a specific feature subset using reconstruction score only.
    selected_features = np.asarray(selected_features, dtype=int)

    if len(selected_features) == 0:
        raise ValueError(f"{experiment_name}: selected feature subset is empty")

    print("=" * 80)
    print(f"AAE baseline experiment: {experiment_name}")
    print(f"Selected features: {len(selected_features)}")

    set_seed(seed)

    train_loader, val_loader, test_loader, preprocessor = make_aae_dataloaders_for_features(selected_features)

    input_dim = len(selected_features)
    model = AAE(input_dim, AAE_LATENT_DIM).to(DEVICE)

    history = train_aae_model(
        model,
        train_loader,
        epochs=epochs,
        device=DEVICE,
        lr_ae=AAE_LR_AE,
        lr_g=AAE_LR_G,
        lr_d=AAE_LR_D,
    )

    scores, labels = compute_aae_reconstruction_scores(model, val_loader, AAE_TOP_K)
    pr_auc = compute_pr_auc(scores=scores, labels=labels)

    row = {
        "experiment": experiment_name,
        "model": "AAE_reconstruction_only",
        "n_features": int(len(selected_features)),
        "pr_auc": pr_auc,
    }

    print(pd.Series(row))

    return {
        "row": row,
        "model": model,
        "history": history,
        "selected_features": selected_features,
        "preprocessor": preprocessor,
        "scores": scores,
        "labels": labels,
    }

## Part C.4 — Build AAE feature subsets: all, nonconstant, correlation-pruned and KS-ranked

In [28]:
aae_all_features = select_all_features(aae_n_features_raw)
aae_nonconstant_features = select_nonconstant_features(aae_splits.x_train, eps=CONSTANT_EPS)
aae_nonconstant_corr_features = correlation_prune_features(
    aae_splits.x_train,
    aae_nonconstant_features,
    threshold=CORR_THRESHOLD,
)

print("AAE all features:                 ", len(aae_all_features))
print("AAE after near-constant removal:  ", len(aae_nonconstant_features))
print("AAE after correlation pruning:    ", len(aae_nonconstant_corr_features))

aae_ks_ranked_features, aae_ks_scores = rank_features_by_ks(
    aae_splits.x_val,
    aae_splits.y_val,
    candidate_features=aae_nonconstant_features,
)

aae_ks_table = pd.DataFrame({
    "rank": np.arange(1, len(aae_ks_ranked_features) + 1),
    "feature_index": aae_ks_ranked_features,
    "feature_name": aae_feature_names[aae_ks_ranked_features],
    "ks_score": aae_ks_scores,
})

aae_selected_feature_tables = {
    "all_features": aae_all_features,
    "nonconstant": aae_nonconstant_features,
    "nonconstant_corr": aae_nonconstant_corr_features,
}

for m in M_VALUES:
    m_eff = min(m, len(aae_ks_ranked_features))
    aae_selected_feature_tables[f"top_{m_eff}_ks"] = aae_ks_ranked_features[:m_eff]

aae_ks_table.head(20)

AAE all features:                  86
AAE after near-constant removal:   82
AAE after correlation pruning:     79

    rank  feature_index                         feature_name  ks_score
0      1             37                        sensor_id3_q1  0.444422
1      2             17                        sensor_id1_q3  0.413103
2      3             15                        sensor_id1_q1  0.411799
3      4             72                        sensor_id6_q3  0.395636
4      5             71                        sensor_id6_q2  0.359868
5      6             38                        sensor_id3_q2  0.357046
6      7              8       machine_nameKuka Robot_voltage  0.335216
7      8             50                        sensor_id4_q3  0.333629
8      9              4   machine_nameKuka Robot_phase_angle  0.308354
9     10              6  machine_nameKuka Robot_power_factor  0.308327
10    11             49                        sensor_id4_q2  0.306350
11    12             48                        sensor_id4_q1  0.287643
12    13             83                        sensor_id7_q3  0.286905
13    14             62                        sensor_id5_q4  0.272725
14    15             18                        sensor_id1_q4  0.262092
15    16             73                        sensor_id6_q4  0.261393
16    17             82                        sensor_id7_q2  0.259256
17    18             60                        sensor_id5_q2  0.237628
18    19             39                        sensor_id3_q3  0.237269
19    20             28                        sensor_id2_q3  0.212113

## Part C.5 — Run AAE baseline experiments for all, nonconstant, correlation-pruned and KS-selected features

In [29]:
aae_experiment_outputs = []

aae_initial_experiments_to_run = [
    "all_features",
    "nonconstant",
    "nonconstant_corr",
    *[f"top_{min(m, len(aae_ks_ranked_features))}_ks" for m in M_VALUES],
]

# Remove duplicate names in case M_VALUES contains values larger than the ranking length.
aae_initial_experiments_to_run = list(dict.fromkeys(aae_initial_experiments_to_run))

for experiment_name in aae_initial_experiments_to_run:
    selected = aae_selected_feature_tables[experiment_name]
    out = run_aae_baseline_experiment(experiment_name, selected, epochs=AAE_EPOCHS, seed=AAE_SEED)
    aae_experiment_outputs.append(out)

================================================================================
AAE baseline experiment: all_features
Selected features: 86
Epoch [1/50] Recon Loss: 0.062115 | D Loss: 2.061319 | G Loss: 1.168327
Epoch [2/50] Recon Loss: 0.027127 | D Loss: 2.051675 | G Loss: 1.154286
Epoch [3/50] Recon Loss: 0.025064 | D Loss: 1.851864 | G Loss: 1.335892
Epoch [4/50] Recon Loss: 0.022908 | D Loss: 1.857308 | G Loss: 1.317682
Epoch [5/50] Recon Loss: 0.022040 | D Loss: 1.917396 | G Loss: 1.242625
Epoch [6/50] Recon Loss: 0.021069 | D Loss: 1.957298 | G Loss: 1.183175
Epoch [7/50] Recon Loss: 0.020738 | D Loss: 1.962135 | G Loss: 1.162479
Epoch [8/50] Recon Loss: 0.019937 | D Loss: 1.950720 | G Loss: 1.180017
Epoch [9/50] Recon Loss: 0.020070 | D Loss: 1.926778 | G Loss: 1.214472
Epoch [10/50] Recon Loss: 0.019437 | D Loss: 1.918271 | G Loss: 1.220688
Epoch [11/50] Recon Loss: 0.018253 | D Loss: 1.924857 | G Loss: 1.206010
Epoch [12/50] Recon Loss: 0.017674 | D Loss: 1.937325 | G Loss: 1.192585
Epoch [13/50] Recon Loss: 0.017334 | D Loss: 1.947445 | G Loss: 1.192913
Epoch [14/50] Recon Loss: 0.017071 | D Loss: 1.948031 | G Loss: 1.204333
Epoch [15/50] Recon Loss: 0.016663 | D Loss: 1.949023 | G Loss: 1.212619
Epoch [16/50] Recon Loss: 0.016330 | D Loss: 1.945592 | G Loss: 1.223496
Epoch [17/50] Recon Loss: 0.016029 | D Loss: 1.940323 | G Loss: 1.230582
Epoch [18/50] Recon Loss: 0.015752 | D Loss: 1.939741 | G Loss: 1.226790
Epoch [19/50] Recon Loss: 0.015450 | D Loss: 1.937750 | G Loss: 1.227300
Epoch [20/50] Recon Loss: 0.015139 | D Loss: 1.939671 | G Loss: 1.227442
Epoch [21/50] Recon Loss: 0.014894 | D Loss: 1.947722 | G Loss: 1.221807
Epoch [22/50] Recon Loss: 0.014728 | D Loss: 1.956742 | G Loss: 1.221983
Epoch [23/50] Recon Loss: 0.014530 | D Loss: 1.959045 | G Loss: 1.232826
Epoch [24/50] Recon Loss: 0.014397 | D Loss: 1.954655 | G Loss: 1.248455
Epoch [25/50] Recon Loss: 0.014246 | D Loss: 1.955969 | G Loss: 1.240480
Epoch [26/50] Recon Loss: 0.014099 | D Loss: 1.956080 | G Loss: 1.235740
Epoch [27/50] Recon Loss: 0.013989 | D Loss: 1.956692 | G Loss: 1.237405
Epoch [28/50] Recon Loss: 0.013868 | D Loss: 1.959101 | G Loss: 1.241977
Epoch [29/50] Recon Loss: 0.013780 | D Loss: 1.959701 | G Loss: 1.249461
Epoch [30/50] Recon Loss: 0.013656 | D Loss: 1.959715 | G Loss: 1.259200
Epoch [31/50] Recon Loss: 0.013571 | D Loss: 1.959310 | G Loss: 1.263805
Epoch [32/50] Recon Loss: 0.013474 | D Loss: 1.959617 | G Loss: 1.260357
Epoch [33/50] Recon Loss: 0.013401 | D Loss: 1.963064 | G Loss: 1.258544
Epoch [34/50] Recon Loss: 0.013286 | D Loss: 1.965307 | G Loss: 1.265336
Epoch [35/50] Recon Loss: 0.013210 | D Loss: 1.967154 | G Loss: 1.272361
Epoch [36/50] Recon Loss: 0.013077 | D Loss: 1.968745 | G Loss: 1.279323
Epoch [37/50] Recon Loss: 0.013015 | D Loss: 1.971714 | G Loss: 1.281008
Epoch [38/50] Recon Loss: 0.012889 | D Loss: 1.977125 | G Loss: 1.276286
Epoch [39/50] Recon Loss: 0.012722 | D Loss: 1.981912 | G Loss: 1.268828
Epoch [40/50] Recon Loss: 0.012556 | D Loss: 1.985165 | G Loss: 1.256313
Epoch [41/50] Recon Loss: 0.012365 | D Loss: 1.985993 | G Loss: 1.253005
Epoch [42/50] Recon Loss: 0.012180 | D Loss: 1.985461 | G Loss: 1.252057
Epoch [43/50] Recon Loss: 0.012037 | D Loss: 1.985102 | G Loss: 1.250611
Epoch [44/50] Recon Loss: 0.011895 | D Loss: 1.985712 | G Loss: 1.250955
Epoch [45/50] Recon Loss: 0.011710 | D Loss: 1.986649 | G Loss: 1.253184
Epoch [46/50] Recon Loss: 0.011551 | D Loss: 1.986650 | G Loss: 1.255865
Epoch [47/50] Recon Loss: 0.011382 | D Loss: 1.987088 | G Loss: 1.253723
Epoch [48/50] Recon Loss: 0.011255 | D Loss: 1.986942 | G Loss: 1.249525
Epoch [49/50] Recon Loss: 0.011124 | D Loss: 1.987541 | G Loss: 1.247293
Epoch [50/50] Recon Loss: 0.010974 | D Loss: 1.987779 | G Loss: 1.245055
experiment               all_features
model         AAE_reconstruction_only
n_features                         86
pr_auc                       0.737292
dtype: object
================================================================================
AAE baseline experiment: nonconstant
Selected features: 82
Epoch [1/50] Recon Loss: 0.061187 | D Loss: 1.989534 | G Loss: 1.055009
Epoch [2/50] Recon Loss: 0.028550 | D Loss: 1.970404 | G Loss: 1.051874
Epoch [3/50] Recon Loss: 0.026758 | D Loss: 1.968880 | G Loss: 1.063776
Epoch [4/50] Recon Loss: 0.024192 | D Loss: 1.825415 | G Loss: 1.210959
Epoch [5/50] Recon Loss: 0.022053 | D Loss: 1.785856 | G Loss: 1.265045
Epoch [6/50] Recon Loss: 0.021376 | D Loss: 1.797138 | G Loss: 1.273765
Epoch [7/50] Recon Loss: 0.020914 | D Loss: 1.831194 | G Loss: 1.258566
Epoch [8/50] Recon Loss: 0.020492 | D Loss: 1.870720 | G Loss: 1.228840
Epoch [9/50] Recon Loss: 0.020082 | D Loss: 1.903191 | G Loss: 1.190932
Epoch [10/50] Recon Loss: 0.019597 | D Loss: 1.922291 | G Loss: 1.165775
Epoch [11/50] Recon Loss: 0.019295 | D Loss: 1.927376 | G Loss: 1.160166
Epoch [12/50] Recon Loss: 0.019115 | D Loss: 1.927680 | G Loss: 1.167403
Epoch [13/50] Recon Loss: 0.018996 | D Loss: 1.923982 | G Loss: 1.188001
Epoch [14/50] Recon Loss: 0.018886 | D Loss: 1.918284 | G Loss: 1.192055
Epoch [15/50] Recon Loss: 0.018773 | D Loss: 1.916097 | G Loss: 1.186730
Epoch [16/50] Recon Loss: 0.018681 | D Loss: 1.915718 | G Loss: 1.178301
Epoch [17/50] Recon Loss: 0.018584 | D Loss: 1.915887 | G Loss: 1.166762
Epoch [18/50] Recon Loss: 0.018496 | D Loss: 1.916396 | G Loss: 1.162918
Epoch [19/50] Recon Loss: 0.018451 | D Loss: 1.917773 | G Loss: 1.152743
Epoch [20/50] Recon Loss: 0.018366 | D Loss: 1.917762 | G Loss: 1.146034
Epoch [21/50] Recon Loss: 0.018300 | D Loss: 1.920124 | G Loss: 1.140157
Epoch [22/50] Recon Loss: 0.018220 | D Loss: 1.942696 | G Loss: 1.110564
Epoch [23/50] Recon Loss: 0.018040 | D Loss: 1.937933 | G Loss: 1.131752
Epoch [24/50] Recon Loss: 0.017895 | D Loss: 1.929395 | G Loss: 1.136495
Epoch [25/50] Recon Loss: 0.017730 | D Loss: 1.933274 | G Loss: 1.103846
Epoch [26/50] Recon Loss: 0.017556 | D Loss: 1.930447 | G Loss: 1.096872
Epoch [27/50] Recon Loss: 0.017376 | D Loss: 1.917056 | G Loss: 1.124230
Epoch [28/50] Recon Loss: 0.017149 | D Loss: 1.917956 | G Loss: 1.122346
Epoch [29/50] Recon Loss: 0.016813 | D Loss: 1.932116 | G Loss: 1.093222
Epoch [30/50] Recon Loss: 0.016548 | D Loss: 1.944166 | G Loss: 1.074329
Epoch [31/50] Recon Loss: 0.016324 | D Loss: 1.939156 | G Loss: 1.076398
Epoch [32/50] Recon Loss: 0.016190 | D Loss: 1.952762 | G Loss: 1.056551
Epoch [33/50] Recon Loss: 0.016022 | D Loss: 1.948696 | G Loss: 1.073632
Epoch [34/50] Recon Loss: 0.015910 | D Loss: 1.944151 | G Loss: 1.079519
Epoch [35/50] Recon Loss: 0.015768 | D Loss: 1.942291 | G Loss: 1.073262
Epoch [36/50] Recon Loss: 0.015672 | D Loss: 1.945143 | G Loss: 1.074874
Epoch [37/50] Recon Loss: 0.015565 | D Loss: 1.948361 | G Loss: 1.095418
Epoch [38/50] Recon Loss: 0.015464 | D Loss: 1.958082 | G Loss: 1.077838
Epoch [39/50] Recon Loss: 0.015390 | D Loss: 1.964526 | G Loss: 1.066012
Epoch [40/50] Recon Loss: 0.015268 | D Loss: 1.954468 | G Loss: 1.099829
Epoch [41/50] Recon Loss: 0.015148 | D Loss: 1.973248 | G Loss: 1.076206
Epoch [42/50] Recon Loss: 0.014991 | D Loss: 1.967876 | G Loss: 1.055136
Epoch [43/50] Recon Loss: 0.014880 | D Loss: 1.955566 | G Loss: 1.076597
Epoch [44/50] Recon Loss: 0.014776 | D Loss: 1.950633 | G Loss: 1.081809
Epoch [45/50] Recon Loss: 0.014717 | D Loss: 1.964000 | G Loss: 1.065606
Epoch [46/50] Recon Loss: 0.014670 | D Loss: 1.982391 | G Loss: 1.060637
Epoch [47/50] Recon Loss: 0.014540 | D Loss: 1.966425 | G Loss: 1.102237
Epoch [48/50] Recon Loss: 0.014406 | D Loss: 1.969206 | G Loss: 1.125448
Epoch [49/50] Recon Loss: 0.014255 | D Loss: 1.968476 | G Loss: 1.149320
Epoch [50/50] Recon Loss: 0.014139 | D Loss: 1.975294 | G Loss: 1.110638
experiment                nonconstant
model         AAE_reconstruction_only
n_features                         82
pr_auc                       0.690494
dtype: object
================================================================================
AAE baseline experiment: nonconstant_corr
Selected features: 79
Epoch [1/50] Recon Loss: 0.065277 | D Loss: 2.015053 | G Loss: 1.111599
Epoch [2/50] Recon Loss: 0.028641 | D Loss: 1.985134 | G Loss: 1.121303
Epoch [3/50] Recon Loss: 0.028417 | D Loss: 1.977296 | G Loss: 1.163527
Epoch [4/50] Recon Loss: 0.027514 | D Loss: 1.913823 | G Loss: 1.280297
Epoch [5/50] Recon Loss: 0.025122 | D Loss: 1.921808 | G Loss: 1.272185
Epoch [6/50] Recon Loss: 0.022934 | D Loss: 1.925894 | G Loss: 1.247632
Epoch [7/50] Recon Loss: 0.021763 | D Loss: 1.920000 | G Loss: 1.232054
Epoch [8/50] Recon Loss: 0.020485 | D Loss: 1.922027 | G Loss: 1.213787
Epoch [9/50] Recon Loss: 0.020030 | D Loss: 1.928652 | G Loss: 1.196897
Epoch [10/50] Recon Loss: 0.019843 | D Loss: 1.933339 | G Loss: 1.187547
Epoch [11/50] Recon Loss: 0.019734 | D Loss: 1.954016 | G Loss: 1.178630
Epoch [12/50] Recon Loss: 0.019687 | D Loss: 1.957482 | G Loss: 1.198224
Epoch [13/50] Recon Loss: 0.019526 | D Loss: 1.924834 | G Loss: 1.239601
Epoch [14/50] Recon Loss: 0.019403 | D Loss: 1.926658 | G Loss: 1.230306
Epoch [15/50] Recon Loss: 0.019264 | D Loss: 1.931994 | G Loss: 1.212199
Epoch [16/50] Recon Loss: 0.019067 | D Loss: 1.927234 | G Loss: 1.208601
Epoch [17/50] Recon Loss: 0.018325 | D Loss: 1.922080 | G Loss: 1.210694
Epoch [18/50] Recon Loss: 0.017651 | D Loss: 1.926876 | G Loss: 1.212218
Epoch [19/50] Recon Loss: 0.017462 | D Loss: 1.930243 | G Loss: 1.218658
Epoch [20/50] Recon Loss: 0.017238 | D Loss: 1.935026 | G Loss: 1.222304
Epoch [21/50] Recon Loss: 0.017045 | D Loss: 1.956760 | G Loss: 1.202752
Epoch [22/50] Recon Loss: 0.016801 | D Loss: 1.924032 | G Loss: 1.231042
Epoch [23/50] Recon Loss: 0.016625 | D Loss: 1.928203 | G Loss: 1.208985
Epoch [24/50] Recon Loss: 0.016380 | D Loss: 1.932029 | G Loss: 1.194246
Epoch [25/50] Recon Loss: 0.016099 | D Loss: 1.928233 | G Loss: 1.198991
Epoch [26/50] Recon Loss: 0.015772 | D Loss: 1.928641 | G Loss: 1.209985
Epoch [27/50] Recon Loss: 0.015536 | D Loss: 1.929482 | G Loss: 1.222981
Epoch [28/50] Recon Loss: 0.015383 | D Loss: 1.931943 | G Loss: 1.232377
Epoch [29/50] Recon Loss: 0.015227 | D Loss: 1.936365 | G Loss: 1.237341
Epoch [30/50] Recon Loss: 0.015145 | D Loss: 1.937347 | G Loss: 1.241364
Epoch [31/50] Recon Loss: 0.015023 | D Loss: 1.937136 | G Loss: 1.242941
Epoch [32/50] Recon Loss: 0.014946 | D Loss: 1.935162 | G Loss: 1.250320
Epoch [33/50] Recon Loss: 0.014879 | D Loss: 1.933097 | G Loss: 1.257272
Epoch [34/50] Recon Loss: 0.014822 | D Loss: 1.931418 | G Loss: 1.262514
Epoch [35/50] Recon Loss: 0.014756 | D Loss: 1.931657 | G Loss: 1.266669
Epoch [36/50] Recon Loss: 0.014695 | D Loss: 1.937906 | G Loss: 1.267473
Epoch [37/50] Recon Loss: 0.014632 | D Loss: 1.940667 | G Loss: 1.269103
Epoch [38/50] Recon Loss: 0.014559 | D Loss: 1.939939 | G Loss: 1.261294
Epoch [39/50] Recon Loss: 0.014489 | D Loss: 1.939160 | G Loss: 1.256353
Epoch [40/50] Recon Loss: 0.014434 | D Loss: 1.942104 | G Loss: 1.262058
Epoch [41/50] Recon Loss: 0.014366 | D Loss: 1.946666 | G Loss: 1.279402
Epoch [42/50] Recon Loss: 0.014293 | D Loss: 1.947762 | G Loss: 1.280032
Epoch [43/50] Recon Loss: 0.014207 | D Loss: 1.949476 | G Loss: 1.273647
Epoch [44/50] Recon Loss: 0.014120 | D Loss: 1.951250 | G Loss: 1.272126
Epoch [45/50] Recon Loss: 0.014063 | D Loss: 1.953551 | G Loss: 1.268854
Epoch [46/50] Recon Loss: 0.014012 | D Loss: 1.956005 | G Loss: 1.263105
Epoch [47/50] Recon Loss: 0.013952 | D Loss: 1.957759 | G Loss: 1.259903
Epoch [48/50] Recon Loss: 0.013923 | D Loss: 1.959839 | G Loss: 1.264051
Epoch [49/50] Recon Loss: 0.013868 | D Loss: 1.963227 | G Loss: 1.273433
Epoch [50/50] Recon Loss: 0.013809 | D Loss: 1.964390 | G Loss: 1.287884
experiment           nonconstant_corr
model         AAE_reconstruction_only
n_features                         79
pr_auc                       0.716179
dtype: object
================================================================================
AAE baseline experiment: top_10_ks
Selected features: 10
Epoch [1/50] Recon Loss: 0.098794 | D Loss: 2.035712 | G Loss: 0.903783
Epoch [2/50] Recon Loss: 0.035447 | D Loss: 2.126651 | G Loss: 0.766225
Epoch [3/50] Recon Loss: 0.020537 | D Loss: 1.648413 | G Loss: 1.218084
Epoch [4/50] Recon Loss: 0.014472 | D Loss: 1.579999 | G Loss: 1.246670
Epoch [5/50] Recon Loss: 0.010292 | D Loss: 1.631791 | G Loss: 1.186029
Epoch [6/50] Recon Loss: 0.007328 | D Loss: 1.655004 | G Loss: 1.161889
Epoch [7/50] Recon Loss: 0.006323 | D Loss: 1.732954 | G Loss: 1.081202
Epoch [8/50] Recon Loss: 0.005878 | D Loss: 1.823432 | G Loss: 0.981908
Epoch [9/50] Recon Loss: 0.005538 | D Loss: 1.892500 | G Loss: 0.895240
Epoch [10/50] Recon Loss: 0.005283 | D Loss: 1.923509 | G Loss: 0.832679
Epoch [11/50] Recon Loss: 0.005156 | D Loss: 1.941355 | G Loss: 0.782368
Epoch [12/50] Recon Loss: 0.004987 | D Loss: 1.951054 | G Loss: 0.743794
Epoch [13/50] Recon Loss: 0.004943 | D Loss: 1.952689 | G Loss: 0.723623
Epoch [14/50] Recon Loss: 0.004870 | D Loss: 1.948330 | G Loss: 0.719031
Epoch [15/50] Recon Loss: 0.004805 | D Loss: 1.951340 | G Loss: 0.713075
Epoch [16/50] Recon Loss: 0.004752 | D Loss: 1.961586 | G Loss: 0.701537
Epoch [17/50] Recon Loss: 0.004727 | D Loss: 1.969791 | G Loss: 0.699020
Epoch [18/50] Recon Loss: 0.004644 | D Loss: 1.965901 | G Loss: 0.716908
Epoch [19/50] Recon Loss: 0.004581 | D Loss: 1.959672 | G Loss: 0.748516
Epoch [20/50] Recon Loss: 0.004600 | D Loss: 1.961323 | G Loss: 0.769918
Epoch [21/50] Recon Loss: 0.004555 | D Loss: 1.955878 | G Loss: 0.798328
Epoch [22/50] Recon Loss: 0.004472 | D Loss: 1.949330 | G Loss: 0.815734
Epoch [23/50] Recon Loss: 0.004468 | D Loss: 1.957958 | G Loss: 0.799047
Epoch [24/50] Recon Loss: 0.004443 | D Loss: 1.957656 | G Loss: 0.809125
Epoch [25/50] Recon Loss: 0.004394 | D Loss: 1.953621 | G Loss: 0.831084
Epoch [26/50] Recon Loss: 0.004480 | D Loss: 1.955616 | G Loss: 0.846294
Epoch [27/50] Recon Loss: 0.004410 | D Loss: 1.957268 | G Loss: 0.865770
Epoch [28/50] Recon Loss: 0.004434 | D Loss: 1.957793 | G Loss: 0.841028
Epoch [29/50] Recon Loss: 0.004675 | D Loss: 1.989735 | G Loss: 0.816814
Epoch [30/50] Recon Loss: 0.004276 | D Loss: 1.968464 | G Loss: 0.921624
Epoch [31/50] Recon Loss: 0.004421 | D Loss: 1.977626 | G Loss: 0.871997
Epoch [32/50] Recon Loss: 0.004348 | D Loss: 1.963088 | G Loss: 0.885778
Epoch [33/50] Recon Loss: 0.004473 | D Loss: 1.985169 | G Loss: 0.864011
Epoch [34/50] Recon Loss: 0.004183 | D Loss: 1.976149 | G Loss: 0.912495
Epoch [35/50] Recon Loss: 0.004427 | D Loss: 1.997315 | G Loss: 0.894942
Epoch [36/50] Recon Loss: 0.004067 | D Loss: 1.974677 | G Loss: 0.918186
Epoch [37/50] Recon Loss: 0.004448 | D Loss: 1.979567 | G Loss: 0.848787
Epoch [38/50] Recon Loss: 0.004288 | D Loss: 1.936568 | G Loss: 0.909153
Epoch [39/50] Recon Loss: 0.004058 | D Loss: 1.984834 | G Loss: 0.883844
Epoch [40/50] Recon Loss: 0.004218 | D Loss: 2.006573 | G Loss: 0.885092
Epoch [41/50] Recon Loss: 0.004165 | D Loss: 1.981959 | G Loss: 0.951486
Epoch [42/50] Recon Loss: 0.003785 | D Loss: 1.980324 | G Loss: 0.925492
Epoch [43/50] Recon Loss: 0.003524 | D Loss: 1.978090 | G Loss: 0.884531
Epoch [44/50] Recon Loss: 0.003438 | D Loss: 1.976058 | G Loss: 0.906682
Epoch [45/50] Recon Loss: 0.003682 | D Loss: 1.986816 | G Loss: 0.932805
Epoch [46/50] Recon Loss: 0.003975 | D Loss: 1.993173 | G Loss: 0.942906
Epoch [47/50] Recon Loss: 0.003314 | D Loss: 1.979229 | G Loss: 0.911024
Epoch [48/50] Recon Loss: 0.003268 | D Loss: 1.996720 | G Loss: 0.900976
Epoch [49/50] Recon Loss: 0.003191 | D Loss: 1.987817 | G Loss: 0.953365
Epoch [50/50] Recon Loss: 0.002986 | D Loss: 1.983874 | G Loss: 0.945454
experiment                  top_10_ks
model         AAE_reconstruction_only
n_features                         10
pr_auc                       0.893346
dtype: object
================================================================================
AAE baseline experiment: top_20_ks
Selected features: 20
Epoch [1/50] Recon Loss: 0.089488 | D Loss: 2.024439 | G Loss: 0.939871
Epoch [2/50] Recon Loss: 0.056067 | D Loss: 1.873951 | G Loss: 1.047879
Epoch [3/50] Recon Loss: 0.036876 | D Loss: 1.750492 | G Loss: 1.205926
Epoch [4/50] Recon Loss: 0.028376 | D Loss: 1.629883 | G Loss: 1.398842
Epoch [5/50] Recon Loss: 0.022570 | D Loss: 1.498944 | G Loss: 1.608190
Epoch [6/50] Recon Loss: 0.020872 | D Loss: 1.573868 | G Loss: 1.564778
Epoch [7/50] Recon Loss: 0.019954 | D Loss: 1.672423 | G Loss: 1.476053
Epoch [8/50] Recon Loss: 0.019414 | D Loss: 1.771272 | G Loss: 1.385931
Epoch [9/50] Recon Loss: 0.018970 | D Loss: 1.835971 | G Loss: 1.326359
Epoch [10/50] Recon Loss: 0.018655 | D Loss: 1.873383 | G Loss: 1.282906
Epoch [11/50] Recon Loss: 0.018887 | D Loss: 1.894797 | G Loss: 1.259231
Epoch [12/50] Recon Loss: 0.018609 | D Loss: 1.923108 | G Loss: 1.224645
Epoch [13/50] Recon Loss: 0.018508 | D Loss: 1.947985 | G Loss: 1.163985
Epoch [14/50] Recon Loss: 0.017865 | D Loss: 2.013424 | G Loss: 1.014188
Epoch [15/50] Recon Loss: 0.017313 | D Loss: 1.977914 | G Loss: 1.045368
Epoch [16/50] Recon Loss: 0.017299 | D Loss: 1.970946 | G Loss: 1.050438
Epoch [17/50] Recon Loss: 0.016566 | D Loss: 1.992052 | G Loss: 1.014160
Epoch [18/50] Recon Loss: 0.016183 | D Loss: 1.960885 | G Loss: 0.994694
Epoch [19/50] Recon Loss: 0.015920 | D Loss: 1.986370 | G Loss: 0.973558
Epoch [20/50] Recon Loss: 0.015858 | D Loss: 1.959891 | G Loss: 1.031109
Epoch [21/50] Recon Loss: 0.015219 | D Loss: 1.977123 | G Loss: 0.964918
Epoch [22/50] Recon Loss: 0.015105 | D Loss: 1.977644 | G Loss: 0.965388
Epoch [23/50] Recon Loss: 0.015023 | D Loss: 1.969522 | G Loss: 0.981171
Epoch [24/50] Recon Loss: 0.014751 | D Loss: 1.978253 | G Loss: 0.980901
Epoch [25/50] Recon Loss: 0.014419 | D Loss: 1.962661 | G Loss: 0.991564
Epoch [26/50] Recon Loss: 0.014419 | D Loss: 1.992760 | G Loss: 0.970941
Epoch [27/50] Recon Loss: 0.014197 | D Loss: 1.950588 | G Loss: 1.021103
Epoch [28/50] Recon Loss: 0.014032 | D Loss: 2.000297 | G Loss: 0.963447
Epoch [29/50] Recon Loss: 0.014166 | D Loss: 1.972194 | G Loss: 1.000960
Epoch [30/50] Recon Loss: 0.014385 | D Loss: 1.983540 | G Loss: 0.987595
Epoch [31/50] Recon Loss: 0.013564 | D Loss: 1.974349 | G Loss: 1.003280
Epoch [32/50] Recon Loss: 0.013644 | D Loss: 1.977855 | G Loss: 0.991809
Epoch [33/50] Recon Loss: 0.013681 | D Loss: 1.987446 | G Loss: 0.990540
Epoch [34/50] Recon Loss: 0.013371 | D Loss: 1.978161 | G Loss: 1.001430
Epoch [35/50] Recon Loss: 0.013308 | D Loss: 1.979419 | G Loss: 0.991632
Epoch [36/50] Recon Loss: 0.013378 | D Loss: 1.987261 | G Loss: 0.980259
Epoch [37/50] Recon Loss: 0.013347 | D Loss: 1.980610 | G Loss: 0.991389
Epoch [38/50] Recon Loss: 0.013174 | D Loss: 1.977076 | G Loss: 1.007301
Epoch [39/50] Recon Loss: 0.013252 | D Loss: 1.977421 | G Loss: 1.011435
Epoch [40/50] Recon Loss: 0.012765 | D Loss: 1.985106 | G Loss: 0.987772
Epoch [41/50] Recon Loss: 0.012678 | D Loss: 1.988825 | G Loss: 0.981513
Epoch [42/50] Recon Loss: 0.012671 | D Loss: 1.977775 | G Loss: 1.003577
Epoch [43/50] Recon Loss: 0.012602 | D Loss: 1.980143 | G Loss: 1.004662
Epoch [44/50] Recon Loss: 0.012583 | D Loss: 1.974565 | G Loss: 1.010325
Epoch [45/50] Recon Loss: 0.012435 | D Loss: 1.991320 | G Loss: 0.984143
Epoch [46/50] Recon Loss: 0.012291 | D Loss: 1.984826 | G Loss: 0.981659
Epoch [47/50] Recon Loss: 0.012211 | D Loss: 1.976634 | G Loss: 0.979136
Epoch [48/50] Recon Loss: 0.012158 | D Loss: 1.980245 | G Loss: 0.978169
Epoch [49/50] Recon Loss: 0.012333 | D Loss: 1.982309 | G Loss: 1.017717
Epoch [50/50] Recon Loss: 0.012236 | D Loss: 1.992414 | G Loss: 1.009444
experiment                  top_20_ks
model         AAE_reconstruction_only
n_features                         20
pr_auc                       0.782199
dtype: object
================================================================================
AAE baseline experiment: top_40_ks
Selected features: 40
Epoch [1/50] Recon Loss: 0.079119 | D Loss: 2.078773 | G Loss: 1.101302

## Part C.6 — Rank features by AAE reconstruction-error separation

This ranking is based on the AAE model trained on the correlation-pruned feature set.

$$
r_j = \frac{\mu_{anom,j}-\mu_{normal,j}}{\sigma_{normal,j}+\epsilon}.
$$

In [30]:
@torch.no_grad()
def rank_features_by_aae_reconstruction_separation(model, val_loader, candidate_features, eps=1e-8):
    # Rank local AAE input columns by reconstruction-error separation and map them to original feature indices.
    model.eval()
    device = next(model.parameters()).device

    normal_errors = []
    anomaly_errors = []

    for x, y in val_loader:
        x = x.float().to(device)
        recon, _ = model(x)
        feature_err = (recon - x).pow(2).detach().cpu()

        y = y.cpu()
        if (y == 0).any():
            normal_errors.append(feature_err[y == 0])
        if (y == 1).any():
            anomaly_errors.append(feature_err[y == 1])

    if not normal_errors or not anomaly_errors:
        raise ValueError("Validation split must contain both normal and anomaly samples.")

    normal_errors = torch.cat(normal_errors, dim=0)
    anomaly_errors = torch.cat(anomaly_errors, dim=0)

    normal_mean = normal_errors.mean(dim=0)
    normal_std = normal_errors.std(dim=0)
    anomaly_mean = anomaly_errors.mean(dim=0)

    separation = ((anomaly_mean - normal_mean) / (normal_std + eps)).numpy()
    order = np.argsort(separation)[::-1]

    candidate_features = np.asarray(candidate_features, dtype=int)
    return candidate_features[order], separation[order]


aae_nc_corr_output = next(out for out in aae_experiment_outputs if out["row"]["experiment"] == "nonconstant_corr")
aae_base_model_for_recon_ranking = aae_nc_corr_output["model"]
aae_base_candidate_features = aae_nonconstant_corr_features

_, aae_val_loader_for_base, _, _ = make_aae_dataloaders_for_features(aae_base_candidate_features)

aae_ranked_features, aae_sep_scores = rank_features_by_aae_reconstruction_separation(
    aae_base_model_for_recon_ranking,
    aae_val_loader_for_base,
    candidate_features=aae_base_candidate_features,
)

aae_sep_table = pd.DataFrame({
    "rank": np.arange(1, len(aae_ranked_features) + 1),
    "feature_index": aae_ranked_features,
    "feature_name": aae_feature_names[aae_ranked_features],
    "aae_reconstruction_separation": aae_sep_scores,
})

aae_sep_table.head(20)

,rank,feature_index,feature_name,aae_reconstruction_separation
0,1,50,sensor_id4_q3,13.970358
1,2,48,sensor_id4_q1,9.518894
2,3,49,sensor_id4_q2,6.876550
3,4,51,sensor_id4_q4,3.262555
4,5,38,sensor_id3_q2,2.289487
5,6,72,sensor_id6_q3,0.643837
6,7,62,sensor_id5_q4,0.550349
7,8,83,sensor_id7_q3,0.550144
8,9,70,sensor_id6_q1,0.370463
9,10,73,sensor_id6_q4,0.364268
10,11,40,sensor_id3_q4,0.353715
11,12,8,machine_nameKuka Robot_voltage,0.349419
12,13,82,sensor_id7_q2,0.349297
13,14,84,sensor_id7_q4,0.321721
14,15,3,machine_nameKuka Robot_frequency,0.314950
15,16,4,machine_nameKuka Robot_phase_angle,0.300211
16,17,71,sensor_id6_q2,0.248013
17,18,28,sensor_id2_q3,0.206264
18,19,27,sensor_id2_q2,0.184002
19,20,0,action,0.174805

## Part C.7 — Run AAE baseline experiments for AAE reconstruction-separation selected features

In [31]:
for m in M_VALUES:
    m_eff = min(m, len(aae_ranked_features))
    selected = aae_ranked_features[:m_eff]
    name = f"top_{m_eff}_aae_recon_sep"
    aae_selected_feature_tables[name] = selected

    out = run_aae_baseline_experiment(name, selected, epochs=AAE_EPOCHS, seed=AAE_SEED)
    aae_experiment_outputs.append(out)

================================================================================
AAE baseline experiment: top_10_aae_recon_sep
Selected features: 10
Epoch [1/50] Recon Loss: 0.105396 | D Loss: 2.052872 | G Loss: 0.890058
Epoch [2/50] Recon Loss: 0.037809 | D Loss: 2.399743 | G Loss: 0.629075
Epoch [3/50] Recon Loss: 0.028738 | D Loss: 1.859593 | G Loss: 1.048289
Epoch [4/50] Recon Loss: 0.022916 | D Loss: 1.758019 | G Loss: 1.107571
Epoch [5/50] Recon Loss: 0.019253 | D Loss: 1.910473 | G Loss: 0.948548
Epoch [6/50] Recon Loss: 0.015614 | D Loss: 1.813195 | G Loss: 1.044460
Epoch [7/50] Recon Loss: 0.013620 | D Loss: 1.777558 | G Loss: 1.070883
Epoch [8/50] Recon Loss: 0.011834 | D Loss: 1.786211 | G Loss: 1.052671
Epoch [9/50] Recon Loss: 0.010390 | D Loss: 1.808551 | G Loss: 1.029460
Epoch [10/50] Recon Loss: 0.009698 | D Loss: 1.833837 | G Loss: 1.008321
Epoch [11/50] Recon Loss: 0.009166 | D Loss: 1.863404 | G Loss: 0.986440
Epoch [12/50] Recon Loss: 0.008694 | D Loss: 1.894221 | G Loss: 0.959121
Epoch [13/50] Recon Loss: 0.008154 | D Loss: 1.914891 | G Loss: 0.935436
Epoch [14/50] Recon Loss: 0.007916 | D Loss: 1.927206 | G Loss: 0.912689
Epoch [15/50] Recon Loss: 0.008285 | D Loss: 1.934947 | G Loss: 0.893579
Epoch [16/50] Recon Loss: 0.008437 | D Loss: 1.939453 | G Loss: 0.892834
Epoch [17/50] Recon Loss: 0.007485 | D Loss: 1.938761 | G Loss: 0.892784
Epoch [18/50] Recon Loss: 0.007053 | D Loss: 1.938895 | G Loss: 0.878433
Epoch [19/50] Recon Loss: 0.006658 | D Loss: 1.938680 | G Loss: 0.865006
Epoch [20/50] Recon Loss: 0.006438 | D Loss: 1.937910 | G Loss: 0.855623
Epoch [21/50] Recon Loss: 0.006266 | D Loss: 1.937848 | G Loss: 0.851219
Epoch [22/50] Recon Loss: 0.005996 | D Loss: 1.938780 | G Loss: 0.849350
Epoch [23/50] Recon Loss: 0.005883 | D Loss: 1.939524 | G Loss: 0.851724
Epoch [24/50] Recon Loss: 0.005830 | D Loss: 1.938838 | G Loss: 0.858535
Epoch [25/50] Recon Loss: 0.005684 | D Loss: 1.938372 | G Loss: 0.866597
Epoch [26/50] Recon Loss: 0.005594 | D Loss: 1.936897 | G Loss: 0.877413
Epoch [27/50] Recon Loss: 0.005562 | D Loss: 1.937537 | G Loss: 0.886400
Epoch [28/50] Recon Loss: 0.005515 | D Loss: 1.939859 | G Loss: 0.892867
Epoch [29/50] Recon Loss: 0.005414 | D Loss: 1.942201 | G Loss: 0.900725
Epoch [30/50] Recon Loss: 0.005357 | D Loss: 1.943840 | G Loss: 0.912604
Epoch [31/50] Recon Loss: 0.005303 | D Loss: 1.945551 | G Loss: 0.922840
Epoch [32/50] Recon Loss: 0.005257 | D Loss: 1.948271 | G Loss: 0.925853
Epoch [33/50] Recon Loss: 0.005211 | D Loss: 1.950172 | G Loss: 0.931648
Epoch [34/50] Recon Loss: 0.005195 | D Loss: 1.951913 | G Loss: 0.941483
Epoch [35/50] Recon Loss: 0.005203 | D Loss: 1.952975 | G Loss: 0.954796
Epoch [36/50] Recon Loss: 0.004998 | D Loss: 1.954093 | G Loss: 0.973846
Epoch [37/50] Recon Loss: 0.005247 | D Loss: 1.955313 | G Loss: 1.004107
Epoch [38/50] Recon Loss: 0.005236 | D Loss: 1.956700 | G Loss: 1.048862
Epoch [39/50] Recon Loss: 0.005024 | D Loss: 1.958192 | G Loss: 1.076227
Epoch [40/50] Recon Loss: 0.005365 | D Loss: 1.963030 | G Loss: 1.086736
Epoch [41/50] Recon Loss: 0.004959 | D Loss: 1.969249 | G Loss: 1.099150
Epoch [42/50] Recon Loss: 0.004999 | D Loss: 1.970201 | G Loss: 1.106031
Epoch [43/50] Recon Loss: 0.004792 | D Loss: 1.965634 | G Loss: 1.111753
Epoch [44/50] Recon Loss: 0.004700 | D Loss: 1.962329 | G Loss: 1.109946
Epoch [45/50] Recon Loss: 0.004660 | D Loss: 1.958739 | G Loss: 1.107407
Epoch [46/50] Recon Loss: 0.004777 | D Loss: 1.957401 | G Loss: 1.108724
Epoch [47/50] Recon Loss: 0.004509 | D Loss: 1.958295 | G Loss: 1.107194
Epoch [48/50] Recon Loss: 0.004354 | D Loss: 1.957766 | G Loss: 1.095931
Epoch [49/50] Recon Loss: 0.004490 | D Loss: 1.960135 | G Loss: 1.106436
Epoch [50/50] Recon Loss: 0.004361 | D Loss: 1.960765 | G Loss: 1.102217
experiment       top_10_aae_recon_sep
model         AAE_reconstruction_only
n_features                         10
pr_auc                       0.862981
dtype: object
================================================================================
AAE baseline experiment: top_20_aae_recon_sep
Selected features: 20
Epoch [1/50] Recon Loss: 0.084570 | D Loss: 2.026263 | G Loss: 0.938323
Epoch [2/50] Recon Loss: 0.039725 | D Loss: 1.907270 | G Loss: 1.029998
Epoch [3/50] Recon Loss: 0.028896 | D Loss: 1.627915 | G Loss: 1.329500
Epoch [4/50] Recon Loss: 0.026140 | D Loss: 1.654726 | G Loss: 1.317943
Epoch [5/50] Recon Loss: 0.024218 | D Loss: 1.727478 | G Loss: 1.259773
Epoch [6/50] Recon Loss: 0.022282 | D Loss: 1.801125 | G Loss: 1.212387
Epoch [7/50] Recon Loss: 0.020866 | D Loss: 1.846626 | G Loss: 1.188628
Epoch [8/50] Recon Loss: 0.020207 | D Loss: 1.874840 | G Loss: 1.157868
Epoch [9/50] Recon Loss: 0.019664 | D Loss: 1.887440 | G Loss: 1.128574
Epoch [10/50] Recon Loss: 0.019204 | D Loss: 1.892315 | G Loss: 1.106129
Epoch [11/50] Recon Loss: 0.018777 | D Loss: 1.897324 | G Loss: 1.086537
Epoch [12/50] Recon Loss: 0.018425 | D Loss: 1.902906 | G Loss: 1.072417
Epoch [13/50] Recon Loss: 0.018107 | D Loss: 1.907082 | G Loss: 1.061131
Epoch [14/50] Recon Loss: 0.017815 | D Loss: 1.912873 | G Loss: 1.051281
Epoch [15/50] Recon Loss: 0.017574 | D Loss: 1.916110 | G Loss: 1.049613
Epoch [16/50] Recon Loss: 0.017332 | D Loss: 1.916885 | G Loss: 1.052419
Epoch [17/50] Recon Loss: 0.017026 | D Loss: 1.918394 | G Loss: 1.056281
Epoch [18/50] Recon Loss: 0.016842 | D Loss: 1.920510 | G Loss: 1.071883
Epoch [19/50] Recon Loss: 0.016673 | D Loss: 1.922450 | G Loss: 1.075228
Epoch [20/50] Recon Loss: 0.016363 | D Loss: 1.922266 | G Loss: 1.080860
Epoch [21/50] Recon Loss: 0.016156 | D Loss: 1.917873 | G Loss: 1.088431
Epoch [22/50] Recon Loss: 0.015911 | D Loss: 1.915089 | G Loss: 1.084698
Epoch [23/50] Recon Loss: 0.015746 | D Loss: 1.914666 | G Loss: 1.079754
Epoch [24/50] Recon Loss: 0.015450 | D Loss: 1.917385 | G Loss: 1.076593
Epoch [25/50] Recon Loss: 0.015280 | D Loss: 1.923124 | G Loss: 1.071074
Epoch [26/50] Recon Loss: 0.015186 | D Loss: 1.931435 | G Loss: 1.066800
Epoch [27/50] Recon Loss: 0.014997 | D Loss: 1.936241 | G Loss: 1.068007
Epoch [28/50] Recon Loss: 0.014841 | D Loss: 1.937843 | G Loss: 1.072433
Epoch [29/50] Recon Loss: 0.014649 | D Loss: 1.937170 | G Loss: 1.077922
Epoch [30/50] Recon Loss: 0.014529 | D Loss: 1.936968 | G Loss: 1.082267
Epoch [31/50] Recon Loss: 0.014376 | D Loss: 1.936384 | G Loss: 1.085638
Epoch [32/50] Recon Loss: 0.014234 | D Loss: 1.935858 | G Loss: 1.089388
Epoch [33/50] Recon Loss: 0.014052 | D Loss: 1.935797 | G Loss: 1.094084
Epoch [34/50] Recon Loss: 0.013939 | D Loss: 1.936434 | G Loss: 1.098619
Epoch [35/50] Recon Loss: 0.013823 | D Loss: 1.936827 | G Loss: 1.102819
Epoch [36/50] Recon Loss: 0.013690 | D Loss: 1.937347 | G Loss: 1.106419
Epoch [37/50] Recon Loss: 0.013584 | D Loss: 1.937918 | G Loss: 1.108082
Epoch [38/50] Recon Loss: 0.013445 | D Loss: 1.937965 | G Loss: 1.108173
Epoch [39/50] Recon Loss: 0.013328 | D Loss: 1.938367 | G Loss: 1.107800
Epoch [40/50] Recon Loss: 0.013126 | D Loss: 1.938715 | G Loss: 1.106809
Epoch [41/50] Recon Loss: 0.013049 | D Loss: 1.939838 | G Loss: 1.102876
Epoch [42/50] Recon Loss: 0.012929 | D Loss: 1.940402 | G Loss: 1.103213
Epoch [43/50] Recon Loss: 0.012739 | D Loss: 1.942350 | G Loss: 1.108043
Epoch [44/50] Recon Loss: 0.012657 | D Loss: 1.943966 | G Loss: 1.110358
Epoch [45/50] Recon Loss: 0.012423 | D Loss: 1.947557 | G Loss: 1.113408
Epoch [46/50] Recon Loss: 0.012349 | D Loss: 1.953846 | G Loss: 1.116391
Epoch [47/50] Recon Loss: 0.012053 | D Loss: 1.951920 | G Loss: 1.130950
Epoch [48/50] Recon Loss: 0.011860 | D Loss: 1.958830 | G Loss: 1.123236
Epoch [49/50] Recon Loss: 0.011718 | D Loss: 1.959606 | G Loss: 1.129286
Epoch [50/50] Recon Loss: 0.011593 | D Loss: 1.957332 | G Loss: 1.139458
experiment       top_20_aae_recon_sep
model         AAE_reconstruction_only
n_features                         20
pr_auc                       0.872348
dtype: object
================================================================================
AAE baseline experiment: top_40_aae_recon_sep
Selected features: 40
Epoch [1/50] Recon Loss: 0.072860 | D Loss: 2.077451 | G Loss: 1.102711
Epoch [2/50] Recon Loss: 0.037888 | D Loss: 1.995157 | G Loss: 1.144509
Epoch [3/50] Recon Loss: 0.031070 | D Loss: 1.890513 | G Loss: 1.267184
Epoch [4/50] Recon Loss: 0.028607 | D Loss: 1.914448 | G Loss: 1.248623
Epoch [5/50] Recon Loss: 0.026526 | D Loss: 1.917552 | G Loss: 1.232610
Epoch [6/50] Recon Loss: 0.025059 | D Loss: 1.912891 | G Loss: 1.219583
Epoch [7/50] Recon Loss: 0.024298 | D Loss: 1.915340 | G Loss: 1.207191
Epoch [8/50] Recon Loss: 0.023679 | D Loss: 1.913301 | G Loss: 1.203447
Epoch [9/50] Recon Loss: 0.023301 | D Loss: 1.911393 | G Loss: 1.201415
Epoch [10/50] Recon Loss: 0.023025 | D Loss: 1.911958 | G Loss: 1.200175
Epoch [11/50] Recon Loss: 0.022659 | D Loss: 1.914478 | G Loss: 1.197943
Epoch [12/50] Recon Loss: 0.022134 | D Loss: 1.916731 | G Loss: 1.197462
Epoch [13/50] Recon Loss: 0.021884 | D Loss: 1.916518 | G Loss: 1.199047
Epoch [14/50] Recon Loss: 0.021617 | D Loss: 1.916516 | G Loss: 1.199579
Epoch [15/50] Recon Loss: 0.021367 | D Loss: 1.919962 | G Loss: 1.194523
Epoch [16/50] Recon Loss: 0.020884 | D Loss: 1.927144 | G Loss: 1.183157
Epoch [17/50] Recon Loss: 0.019779 | D Loss: 1.935051 | G Loss: 1.168526
Epoch [18/50] Recon Loss: 0.019063 | D Loss: 1.935901 | G Loss: 1.163845
Epoch [19/50] Recon Loss: 0.018697 | D Loss: 1.935699 | G Loss: 1.158365
Epoch [20/50] Recon Loss: 0.018459 | D Loss: 1.935295 | G Loss: 1.151543
Epoch [21/50] Recon Loss: 0.018196 | D Loss: 1.932644 | G Loss: 1.151060
Epoch [22/50] Recon Loss: 0.018050 | D Loss: 1.930765 | G Loss: 1.153449
Epoch [23/50] Recon Loss: 0.017793 | D Loss: 1.929312 | G Loss: 1.153889
Epoch [24/50] Recon Loss: 0.017533 | D Loss: 1.929469 | G Loss: 1.152385
Epoch [25/50] Recon Loss: 0.017381 | D Loss: 1.930197 | G Loss: 1.150509
Epoch [26/50] Recon Loss: 0.017219 | D Loss: 1.932048 | G Loss: 1.149684
Epoch [27/50] Recon Loss: 0.017037 | D Loss: 1.934354 | G Loss: 1.149208
Epoch [28/50] Recon Loss: 0.016989 | D Loss: 1.935922 | G Loss: 1.146115
Epoch [29/50] Recon Loss: 0.016788 | D Loss: 1.937178 | G Loss: 1.141747
Epoch [30/50] Recon Loss: 0.016608 | D Loss: 1.939833 | G Loss: 1.135241
Epoch [31/50] Recon Loss: 0.016493 | D Loss: 1.942641 | G Loss: 1.127033
Epoch [32/50] Recon Loss: 0.016383 | D Loss: 1.945378 | G Loss: 1.120748
Epoch [33/50] Recon Loss: 0.016245 | D Loss: 1.947200 | G Loss: 1.120757
Epoch [34/50] Recon Loss: 0.016174 | D Loss: 1.949957 | G Loss: 1.122932
Epoch [35/50] Recon Loss: 0.015877 | D Loss: 1.953590 | G Loss: 1.125184
Epoch [36/50] Recon Loss: 0.015726 | D Loss: 1.956961 | G Loss: 1.124882
Epoch [37/50] Recon Loss: 0.015583 | D Loss: 1.960848 | G Loss: 1.125018
Epoch [38/50] Recon Loss: 0.015460 | D Loss: 1.963171 | G Loss: 1.123476
Epoch [39/50] Recon Loss: 0.015312 | D Loss: 1.964632 | G Loss: 1.121267
Epoch [40/50] Recon Loss: 0.015191 | D Loss: 1.965428 | G Loss: 1.122198
Epoch [41/50] Recon Loss: 0.014976 | D Loss: 1.965896 | G Loss: 1.126083
Epoch [42/50] Recon Loss: 0.014850 | D Loss: 1.966809 | G Loss: 1.127355
Epoch [43/50] Recon Loss: 0.014621 | D Loss: 1.968759 | G Loss: 1.129552
Epoch [44/50] Recon Loss: 0.014405 | D Loss: 1.970706 | G Loss: 1.129648
Epoch [45/50] Recon Loss: 0.014586 | D Loss: 1.973027 | G Loss: 1.131274
Epoch [46/50] Recon Loss: 0.013952 | D Loss: 1.976442 | G Loss: 1.129560
Epoch [47/50] Recon Loss: 0.013542 | D Loss: 1.977840 | G Loss: 1.124986
Epoch [48/50] Recon Loss: 0.013034 | D Loss: 1.978829 | G Loss: 1.120056
Epoch [49/50] Recon Loss: 0.012654 | D Loss: 1.979922 | G Loss: 1.121790
Epoch [50/50] Recon Loss: 0.012309 | D Loss: 1.980797 | G Loss: 1.126746
experiment       top_40_aae_recon_sep
model         AAE_reconstruction_only
n_features                         40
pr_auc                       0.817864
dtype: object
================================================================================
AAE baseline experiment: top_60_aae_recon_sep
Selected features: 60
Epoch [1/50] Recon Loss: 0.068566 | D Loss: 1.986513 | G Loss: 1.027747
Epoch [2/50] Recon Loss: 0.032310 | D Loss: 1.971319 | G Loss: 1.007414
Epoch [3/50] Recon Loss: 0.027123 | D Loss: 2.010826 | G Loss: 0.939837
Epoch [4/50] Recon Loss: 0.024702 | D Loss: 1.742849 | G Loss: 1.163215
Epoch [5/50] Recon Loss: 0.022913 | D Loss: 1.762714 | G Loss: 1.128643
Epoch [6/50] Recon Loss: 0.021112 | D Loss: 1.855350 | G Loss: 1.040696
Epoch [7/50] Recon Loss: 0.019257 | D Loss: 1.877194 | G Loss: 1.031976
Epoch [8/50] Recon Loss: 0.018770 | D Loss: 1.895933 | G Loss: 1.019137
Epoch [9/50] Recon Loss: 0.018314 | D Loss: 1.935445 | G Loss: 0.979186
Epoch [10/50] Recon Loss: 0.017719 | D Loss: 1.941182 | G Loss: 0.970547
Epoch [11/50] Recon Loss: 0.017279 | D Loss: 1.941369 | G Loss: 0.971582
Epoch [12/50] Recon Loss: 0.017002 | D Loss: 1.941535 | G Loss: 0.976428
Epoch [13/50] Recon Loss: 0.016788 | D Loss: 1.940373 | G Loss: 0.982946
Epoch [14/50] Recon Loss: 0.016615 | D Loss: 1.941373 | G Loss: 0.992632
Epoch [15/50] Recon Loss: 0.016276 | D Loss: 1.939464 | G Loss: 1.011902
Epoch [16/50] Recon Loss: 0.016018 | D Loss: 1.936531 | G Loss: 1.031420
Epoch [17/50] Recon Loss: 0.015678 | D Loss: 1.936892 | G Loss: 1.041698
Epoch [18/50] Recon Loss: 0.015434 | D Loss: 1.940794 | G Loss: 1.049453
Epoch [19/50] Recon Loss: 0.015206 | D Loss: 1.943864 | G Loss: 1.057046
Epoch [20/50] Recon Loss: 0.015024 | D Loss: 1.947569 | G Loss: 1.060968
Epoch [21/50] Recon Loss: 0.014848 | D Loss: 1.949649 | G Loss: 1.062483
Epoch [22/50] Recon Loss: 0.014787 | D Loss: 1.950533 | G Loss: 1.059684
Epoch [23/50] Recon Loss: 0.014579 | D Loss: 1.951758 | G Loss: 1.051736
Epoch [24/50] Recon Loss: 0.014440 | D Loss: 1.953742 | G Loss: 1.045589
Epoch [25/50] Recon Loss: 0.014415 | D Loss: 1.957592 | G Loss: 1.034766
Epoch [26/50] Recon Loss: 0.014161 | D Loss: 1.958691 | G Loss: 1.027291
Epoch [27/50] Recon Loss: 0.014054 | D Loss: 1.959055 | G Loss: 1.024307
Epoch [28/50] Recon Loss: 0.013903 | D Loss: 1.958121 | G Loss: 1.025349
Epoch [29/50] Recon Loss: 0.013850 | D Loss: 1.956397 | G Loss: 1.030943
Epoch [30/50] Recon Loss: 0.013693 | D Loss: 1.953980 | G Loss: 1.040458
Epoch [31/50] Recon Loss: 0.013585 | D Loss: 1.953085 | G Loss: 1.047735
Epoch [32/50] Recon Loss: 0.013471 | D Loss: 1.954796 | G Loss: 1.043908
Epoch [33/50] Recon Loss: 0.013432 | D Loss: 1.956439 | G Loss: 1.038262
Epoch [34/50] Recon Loss: 0.013163 | D Loss: 1.961440 | G Loss: 1.031903
Epoch [35/50] Recon Loss: 0.013114 | D Loss: 1.966235 | G Loss: 1.027838
Epoch [36/50] Recon Loss: 0.013188 | D Loss: 1.969847 | G Loss: 1.028832
Epoch [37/50] Recon Loss: 0.013029 | D Loss: 1.973768 | G Loss: 1.025474
Epoch [38/50] Recon Loss: 0.012986 | D Loss: 1.981495 | G Loss: 1.030170
Epoch [39/50] Recon Loss: 0.012789 | D Loss: 1.977722 | G Loss: 1.057757
Epoch [40/50] Recon Loss: 0.012652 | D Loss: 1.974408 | G Loss: 1.062206
Epoch [41/50] Recon Loss: 0.012436 | D Loss: 1.973130 | G Loss: 1.058518
Epoch [42/50] Recon Loss: 0.012386 | D Loss: 1.974074 | G Loss: 1.054727
Epoch [43/50] Recon Loss: 0.012206 | D Loss: 1.976765 | G Loss: 1.051290
Epoch [44/50] Recon Loss: 0.012013 | D Loss: 1.977300 | G Loss: 1.055435
Epoch [45/50] Recon Loss: 0.011941 | D Loss: 1.978848 | G Loss: 1.042208
Epoch [46/50] Recon Loss: 0.011825 | D Loss: 1.981564 | G Loss: 1.030386
Epoch [47/50] Recon Loss: 0.011626 | D Loss: 1.983918 | G Loss: 1.030818
Epoch [48/50] Recon Loss: 0.011437 | D Loss: 1.985734 | G Loss: 1.034596
Epoch [49/50] Recon Loss: 0.011388 | D Loss: 1.986813 | G Loss: 1.043827
Epoch [50/50] Recon Loss: 0.011173 | D Loss: 1.987402 | G Loss: 1.059736
experiment       top_60_aae_recon_sep
model         AAE_reconstruction_only
n_features                         60
pr_auc                        0.78492
dtype: object

## Part C.8 — AAE baseline results summary

In [32]:
aae_results_df = pd.DataFrame([out["row"] for out in aae_experiment_outputs])
aae_results_df.sort_values("pr_auc", ascending=False)

              experiment                    model  n_features    pr_auc
3              top_10_ks  AAE_reconstruction_only          10  0.893346
8   top_20_aae_recon_sep  AAE_reconstruction_only          20  0.872348
7   top_10_aae_recon_sep  AAE_reconstruction_only          10  0.862981
9   top_40_aae_recon_sep  AAE_reconstruction_only          40  0.817864
6              top_60_ks  AAE_reconstruction_only          60  0.796203
5              top_40_ks  AAE_reconstruction_only          40  0.787968
10  top_60_aae_recon_sep  AAE_reconstruction_only          60  0.784920
4              top_20_ks  AAE_reconstruction_only          20  0.782199
0           all_features  AAE_reconstruction_only          86  0.737292
2       nonconstant_corr  AAE_reconstruction_only          79  0.716179
1            nonconstant  AAE_reconstruction_only          82  0.690494

## Part C.9 — Save AAE feature-selection outputs

The AAE output files are separate from the AE output files.

In [34]:
aae_results_df.to_csv(AAE_RESULTS_PATH, index=False)

aae_ks_table.to_csv(AAE_KS_PATH, index=False)
aae_sep_table.to_csv(AAE_RECON_SEP_PATH, index=False)

aae_selected_rows = []
for experiment, indices in aae_selected_feature_tables.items():
    for rank, idx in enumerate(indices, start=1):
        aae_selected_rows.append({
            "experiment": experiment,
            "rank": rank,
            "feature_index": int(idx),
            "feature_name": str(aae_feature_names[idx]),
        })

aae_selected_df = pd.DataFrame(aae_selected_rows)
aae_selected_df.to_csv(AAE_SELECTED_PATH, index=False)

print("Saved AAE baseline feature-selection outputs.")

Saved AAE baseline feature-selection outputs.

## Part C.10 — Inspect AAE selected features

Use this cell to inspect the feature names selected by any AAE experiment.

In [ ]:
AAE_EXPERIMENT_TO_INSPECT = "top_10_ks_sep"

if AAE_EXPERIMENT_TO_INSPECT in aae_selected_feature_tables:
    idx = aae_selected_feature_tables[AAE_EXPERIMENT_TO_INSPECT]
    display(pd.DataFrame({
        "rank": np.arange(1, len(idx) + 1),
        "feature_index": idx,
        "feature_name": aae_feature_names[idx],
    }))
else:
    print(f"Unknown AAE experiment: {AAE_EXPERIMENT_TO_INSPECT}")
    print("Available AAE experiments:")
    print(sorted(aae_selected_feature_tables.keys()))

   rank  feature_index   feature_name
0     1             50  sensor_id4_q3
1     2             48  sensor_id4_q1
2     3             49  sensor_id4_q2
3     4             51  sensor_id4_q4
4     5             38  sensor_id3_q2
5     6             72  sensor_id6_q3
6     7             62  sensor_id5_q4
7     8             83  sensor_id7_q3
8     9             70  sensor_id6_q1
9    10             73  sensor_id6_q4